"""add_worker_job_table

Revision ID: 4e006ea0acfe
Revises: 0001
Create Date: 2026-07-23 22:04:28.851426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e006ea0acfe'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('enqueued', 'processing', 'completed', 'failed', name='job_status'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('enqueued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product_monitored.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_job_celery_task_id'), 'worker_job', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_worker_job_id'), 'worker_job', ['id'], unique=False)
    op.create_index(op.f('ix_worker_job_product_id'), 'worker_job', ['product_id'], unique=False)
    op.create_index(op.f('ix_worker_job_status'), 'worker_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_job_status'), table_name='worker_job')
    op.drop_index(op.f('ix_worker_job_product_id'), table_name='worker_job')
    op.drop_index(op.f('ix_worker_job_id'), table_name='worker_job')
    op.drop_index(op.f('ix_worker_job_celery_task_id'), table_name='worker_job')
    op.drop_table('worker_job')
    # ### end Alembic commands ###
